FROM node:latest

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/okay

WORKDIR /root/okay/

RUN npm install --silent
RUN npm install -g webpack-dev-server --silent

ENV API_HOST api

EXPOSE 80

CMD ["npm", "start"]
