FROM node:latest

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/okay

WORKDIR /root/okay/

RUN npm install -g webpack-dev-server yarn --silent
RUN yarn install

RUN yarn autoclean

ENV API_HOST api

EXPOSE 80

CMD ["npm", "start"]
